plugins {
    id 'base'
    id 'fabric-loom' version "${loom_version}"
}

version = file('../version.txt').text.trim()

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft}"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	mappings "net.fabricmc:yarn:${yarn_mappings}:v2"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    filesMatching(['quilt.mod.json', 'fabric.mod.json']) {
        expand 'version': version
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    from('../LICENSE') {
        rename { "${it}_blahaj" }
    }
    from('../common')
}

sourceSets {
	main {
		resources {
			srcDir '../common'
		}
	}
}
